### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:32200

### ISSUE THREAD

**Issue by emum8** [ethereum/swarm-dapps#4]
**I get this error in the console:**
angular.js:11821 GET http://localhost:8888/bzzr:/ 500 (Internal Server Error)

**and this in the servers console:**
Error: connect ECONNREFUSED 127.0.0.1:32200
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

**Comment by 0mkara** [comment]
geth and swarm running at background ?
